name: personal_website
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  flutter_cache_manager: ^3.4.1
  parallax_animation: ^0.0.3
  open_file: ^3.5.10
  path_provider: ^2.1.1
  dio: ^5.8.0+1
  permission_handler: ^12.0.0+1
  syncfusion_flutter_pdfviewer: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/pdf/
    - assets/pdf/Abir_Cherif_CV_2025.pdf


