name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'build/web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release
    
    - name: Deploy to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build/web -f
        git commit -m "Deploy to GitHub Pages" || exit 0
        git push origin main 